package com.example.infra.po;

import java.util.Date;

public class TaskRecordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_record.task_id
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_record.task_type
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    private String taskType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_record.task_status
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    private String taskStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_record.task_context
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    private String taskContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_record.next_exe_time
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    private Date nextExeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_record.exe_times
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    private Integer exeTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_record.gmt_created
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_record.gmt_modified
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_record.task_id
     *
     * @return the value of task_record.task_id
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_record.task_id
     *
     * @param taskId the value for task_record.task_id
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_record.task_type
     *
     * @return the value of task_record.task_type
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_record.task_type
     *
     * @param taskType the value for task_record.task_type
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    public void setTaskType(String taskType) {
        this.taskType = taskType == null ? null : taskType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_record.task_status
     *
     * @return the value of task_record.task_status
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_record.task_status
     *
     * @param taskStatus the value for task_record.task_status
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    public void setTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus == null ? null : taskStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_record.task_context
     *
     * @return the value of task_record.task_context
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    public String getTaskContext() {
        return taskContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_record.task_context
     *
     * @param taskContext the value for task_record.task_context
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    public void setTaskContext(String taskContext) {
        this.taskContext = taskContext == null ? null : taskContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_record.next_exe_time
     *
     * @return the value of task_record.next_exe_time
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    public Date getNextExeTime() {
        return nextExeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_record.next_exe_time
     *
     * @param nextExeTime the value for task_record.next_exe_time
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    public void setNextExeTime(Date nextExeTime) {
        this.nextExeTime = nextExeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_record.exe_times
     *
     * @return the value of task_record.exe_times
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    public Integer getExeTimes() {
        return exeTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_record.exe_times
     *
     * @param exeTimes the value for task_record.exe_times
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    public void setExeTimes(Integer exeTimes) {
        this.exeTimes = exeTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_record.gmt_created
     *
     * @return the value of task_record.gmt_created
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_record.gmt_created
     *
     * @param gmtCreated the value for task_record.gmt_created
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_record.gmt_modified
     *
     * @return the value of task_record.gmt_modified
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_record.gmt_modified
     *
     * @param gmtModified the value for task_record.gmt_modified
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}