package com.example.infra.dao.auto;

import com.example.infra.po.TaskRecordDO;
import java.util.List;

public interface TaskRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_record
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    int insert(TaskRecordDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_record
     *
     * @mbg.generated Sat Mar 18 13:57:05 CST 2023
     */
    List<TaskRecordDO> selectAll();
}