package com.example.infra.dao.auto;

import com.example.infra.po.TaskRecordDO;
import com.example.infra.po.TaskRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_record
     *
     * @mbg.generated Sun Mar 19 23:54:53 CST 2023
     */
    long countByExample(TaskRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_record
     *
     * @mbg.generated Sun Mar 19 23:54:53 CST 2023
     */
    int deleteByExample(TaskRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_record
     *
     * @mbg.generated Sun Mar 19 23:54:53 CST 2023
     */
    int insert(TaskRecordDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_record
     *
     * @mbg.generated Sun Mar 19 23:54:53 CST 2023
     */
    int insertSelective(TaskRecordDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_record
     *
     * @mbg.generated Sun Mar 19 23:54:53 CST 2023
     */
    List<TaskRecordDO> selectByExample(TaskRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_record
     *
     * @mbg.generated Sun Mar 19 23:54:53 CST 2023
     */
    int updateByExampleSelective(@Param("row") TaskRecordDO row, @Param("example") TaskRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_record
     *
     * @mbg.generated Sun Mar 19 23:54:53 CST 2023
     */
    int updateByExample(@Param("row") TaskRecordDO row, @Param("example") TaskRecordDOExample example);
}